FROM microsoft/dotnet:2.1-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 57155
EXPOSE 44347

FROM microsoft/dotnet:2.1-sdk AS build
WORKDIR /src
COPY ["src/ApiGateways/Web.BFF/Web.BFF.csproj", "src/ApiGateways/Web.BFF/"]
RUN dotnet restore "src/ApiGateways/Web.BFF/Web.BFF.csproj"
COPY . .
WORKDIR "/src/src/ApiGateways/Web.BFF"
RUN dotnet build "Web.BFF.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "Web.BFF.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "Web.BFF.dll"]